-ifndef(__TTY_BOXCHAR__HRL__).
-define(__TTY_BOXCHAR__HRL__, true).
%%
%% Light and heavy solid lines
%%
-define(BOX_DRAWINGS_LIGHT_HORIZONTAL, 16#2500). %% ─ 
-define(BOX_DRAWINGS_HEAVY_HORIZONTAL, 16#2501). %% ━ 
-define(BOX_DRAWINGS_LIGHT_VERTICAL, 16#2502).   %% │ 
-define(BOX_DRAWINGS_HEAVY_VERTICAL, 16#2503).   %% ┃ 
%% Light and heavy dashed lines
-define(BOX_DRAWINGS_LIGHT_TRIPLE_DASH_HORIZONTAL, 16#2504). %% ┄ 
-define(BOX_DRAWINGS_HEAVY_TRIPLE_DASH_HORIZONTAL, 16#2505). %% ┅ 
-define(BOX_DRAWINGS_LIGHT_TRIPLE_DASH_VERTICAL, 16#2506).   %% ┆ 
-define(BOX_DRAWINGS_HEAVY_TRIPLE_DASH_VERTICAL, 16#2507).   %% ┇ 
-define(BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_HORIZONTAL, 16#2508). %% ┈ 
-define(BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_HORIZONTAL, 16#2509). %% ┉ 
-define(BOX_DRAWINGS_LIGHT_QUADRUPLE_DASH_VERTICAL, 16#250A).   %% ┊ 
-define(BOX_DRAWINGS_HEAVY_QUADRUPLE_DASH_VERTICAL, 16#250B).   %% ┋ 
%%
%% Light and heavy line box components
%%
-define(BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT, 16#250C).       %% ┌ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_HEAVY, 16#250D). %% ┍ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_LIGHT, 16#250E). %% ┎ 
-define(BOX_DRAWINGS_HEAVY_DOWN_AND_RIGHT, 16#250F).       %% ┏ 
-define(BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT, 16#2510).        %% ┐ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_HEAVY, 16#2511).  %% ┑ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_LIGHT, 16#2512).  %% ┒ 
-define(BOX_DRAWINGS_HEAVY_DOWN_AND_LEFT, 16#2513).        %% ┓ 
-define(BOX_DRAWINGS_LIGHT_UP_AND_RIGHT, 16#2514).         %% └ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_HEAVY, 16#2515).   %% ┕ 
-define(BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_LIGHT, 16#2516).   %% ┖ 
-define(BOX_DRAWINGS_HEAVY_UP_AND_RIGHT, 16#2517).         %% ┗ 
-define(BOX_DRAWINGS_LIGHT_UP_AND_LEFT, 16#2518).          %% ┘ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_LEFT_HEAVY, 16#2519).    %% ┙ 
-define(BOX_DRAWINGS_UP_HEAVY_AND_LEFT_LIGHT, 16#251A).    %% ┚ 
-define(BOX_DRAWINGS_HEAVY_UP_AND_LEFT, 16#251B).          %% ┛ 
-define(BOX_DRAWINGS_LIGHT_VERTICAL_AND_RIGHT, 16#251C).   %% ├ 
-define(BOX_DRAWINGS_VERTICAL_LIGHT_AND_RIGHT_HEAVY, 16#251D). %% ┝ 
-define(BOX_DRAWINGS_UP_HEAVY_AND_RIGHT_DOWN_LIGHT, 16#251E).  %% ┞ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_RIGHT_UP_LIGHT, 16#251F).  %% ┟ 
-define(BOX_DRAWINGS_VERTICAL_HEAVY_AND_RIGHT_LIGHT, 16#2520). %% ┠ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_RIGHT_UP_HEAVY, 16#2521).  %% ┡ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_RIGHT_DOWN_HEAVY, 16#2522).  %% ┢ 
-define(BOX_DRAWINGS_HEAVY_VERTICAL_AND_RIGHT, 16#2523).       %% ┣ 
-define(BOX_DRAWINGS_LIGHT_VERTICAL_AND_LEFT, 16#2524).        %% ┤ 
-define(BOX_DRAWINGS_VERTICAL_LIGHT_AND_LEFT_HEAVY, 16#2525). %%  ┥
-define(BOX_DRAWINGS_UP_HEAVY_AND_LEFT_DOWN_LIGHT, 16#2526).   %% ┦ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_LEFT_UP_LIGHT, 16#2527).   %% ┧ 
-define(BOX_DRAWINGS_VERTICAL_HEAVY_AND_LEFT_LIGHT, 16#2528).  %% ┨ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_LEFT_UP_HEAVY, 16#2529).   %% ┩ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_LEFT_DOWN_HEAVY, 16#252A).   %% ┪ 
-define(BOX_DRAWINGS_HEAVY_VERTICAL_AND_LEFT, 16#252B).        %% ┫ 
-define(BOX_DRAWINGS_LIGHT_DOWN_AND_HORIZONTAL, 16#252C).      %% ┬ 
-define(BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_DOWN_LIGHT, 16#252D). %% ┭ 
-define(BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_DOWN_LIGHT, 16#252E). %% ┮ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_HORIZONTAL_HEAVY, 16#252F). %% ┯ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_HORIZONTAL_LIGHT, 16#2530). %% ┰ 
-define(BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_DOWN_HEAVY, 16#2531). %% ┱ 
-define(BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_DOWN_HEAVY, 16#2532). %% ┲ 
-define(BOX_DRAWINGS_HEAVY_DOWN_AND_HORIZONTAL, 16#2533). %% ┳ 
-define(BOX_DRAWINGS_LIGHT_UP_AND_HORIZONTAL, 16#2534). %% ┴ 
-define(BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_UP_LIGHT, 16#2535). %% ┵ 
-define(BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_UP_LIGHT, 16#2536). %% ┶ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_HORIZONTAL_HEAVY, 16#2537). %% ┷ 
-define(BOX_DRAWINGS_UP_HEAVY_AND_HORIZONTAL_LIGHT, 16#2538). %% ┸ 
-define(BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_UP_HEAVY, 16#2539). %% ┹ 
-define(BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_UP_HEAVY, 16#253A). %% ┺ 
-define(BOX_DRAWINGS_HEAVY_UP_AND_HORIZONTAL, 16#253B). %% ┻ 
-define(BOX_DRAWINGS_LIGHT_VERTICAL_AND_HORIZONTAL, 16#253C). %% ┼ 
-define(BOX_DRAWINGS_LEFT_HEAVY_AND_RIGHT_VERTICAL_LIGHT, 16#253D). %% ┽ 
-define(BOX_DRAWINGS_RIGHT_HEAVY_AND_LEFT_VERTICAL_LIGHT, 16#253E). %% ┾ 
-define(BOX_DRAWINGS_VERTICAL_LIGHT_AND_HORIZONTAL_HEAVY, 16#253F). %% ┿ 
-define(BOX_DRAWINGS_UP_HEAVY_AND_DOWN_HORIZONTAL_LIGHT, 16#2540).   %%  ╀ 
-define(BOX_DRAWINGS_DOWN_HEAVY_AND_UP_HORIZONTAL_LIGHT, 16#2541). %% ╁ 
-define(BOX_DRAWINGS_VERTICAL_HEAVY_AND_HORIZONTAL_LIGHT, 16#2542). %% ╂ 
-define(BOX_DRAWINGS_LEFT_UP_HEAVY_AND_RIGHT_DOWN_LIGHT, 16#2543). %% ╃ 
-define(BOX_DRAWINGS_RIGHT_UP_HEAVY_AND_LEFT_DOWN_LIGHT, 16#2544). %% ╄ 
-define(BOX_DRAWINGS_LEFT_DOWN_HEAVY_AND_RIGHT_UP_LIGHT, 16#2545). %% ╅ 
-define(BOX_DRAWINGS_RIGHT_DOWN_HEAVY_AND_LEFT_UP_LIGHT, 16#2546). %% ╆ 
-define(BOX_DRAWINGS_DOWN_LIGHT_AND_UP_HORIZONTAL_HEAVY, 16#2547). %% ╇ 
-define(BOX_DRAWINGS_UP_LIGHT_AND_DOWN_HORIZONTAL_HEAVY, 16#2548). %% ╈ 
-define(BOX_DRAWINGS_RIGHT_LIGHT_AND_LEFT_VERTICAL_HEAVY, 16#2549). %% ╉ 
-define(BOX_DRAWINGS_LEFT_LIGHT_AND_RIGHT_VERTICAL_HEAVY, 16#254A). %% ╊ 
-define(BOX_DRAWINGS_HEAVY_VERTICAL_AND_HORIZONTAL, 16#254B). %% ╋ 
%%
%% Light and heavy dashed lines
%%
-define(BOX_DRAWINGS_LIGHT_DOUBLE_DASH_HORIZONTAL, 16#254C). %% ╌ 
-define(BOX_DRAWINGS_HEAVY_DOUBLE_DASH_HORIZONTAL, 16#254D). %% ╍ 
-define(BOX_DRAWINGS_LIGHT_DOUBLE_DASH_VERTICAL, 16#254E). %% ╎ 
-define(BOX_DRAWINGS_HEAVY_DOUBLE_DASH_VERTICAL, 16#254F). %% ╏ 
%%
%% Double lines
%%
-define(BOX_DRAWINGS_DOUBLE_HORIZONTAL, 16#2550). %% ═ 
-define(BOX_DRAWINGS_DOUBLE_VERTICAL, 16#2551). %% ║ 
%%
%% Light and double line box components
%%
-define(BOX_DRAWINGS_DOWN_SINGLE_AND_RIGHT_DOUBLE, 16#2552). %% ╒ 
-define(BOX_DRAWINGS_DOWN_DOUBLE_AND_RIGHT_SINGLE, 16#2553). %% ╓ 
-define(BOX_DRAWINGS_DOUBLE_DOWN_AND_RIGHT, 16#2554). %% ╔ 
-define(BOX_DRAWINGS_DOWN_SINGLE_AND_LEFT_DOUBLE, 16#2555). %% ╕ 
-define(BOX_DRAWINGS_DOWN_DOUBLE_AND_LEFT_SINGLE, 16#2556). %% ╖ 
-define(BOX_DRAWINGS_DOUBLE_DOWN_AND_LEFT, 16#2557). %% ╗ 
-define(BOX_DRAWINGS_UP_SINGLE_AND_RIGHT_DOUBLE, 16#2558). %% ╘ 
-define(BOX_DRAWINGS_UP_DOUBLE_AND_RIGHT_SINGLE, 16#2559). %% ╙ 
-define(BOX_DRAWINGS_DOUBLE_UP_AND_RIGHT, 16#255A). %% ╚ 
-define(BOX_DRAWINGS_UP_SINGLE_AND_LEFT_DOUBLE, 16#255B). %% ╛ 
-define(BOX_DRAWINGS_UP_DOUBLE_AND_LEFT_SINGLE, 16#255C). %% ╜ 
-define(BOX_DRAWINGS_DOUBLE_UP_AND_LEFT, 16#255D). %% ╝ 
-define(BOX_DRAWINGS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE, 16#255E). %% ╞ 
-define(BOX_DRAWINGS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE, 16#255F). %% ╟ 
-define(BOX_DRAWINGS_DOUBLE_VERTICAL_AND_RIGHT, 16#2560). %% ╠ 
-define(BOX_DRAWINGS_VERTICAL_SINGLE_AND_LEFT_DOUBLE, 16#2561). %% ╡ 
-define(BOX_DRAWINGS_VERTICAL_DOUBLE_AND_LEFT_SINGLE, 16#2562). %% ╢ 
-define(BOX_DRAWINGS_DOUBLE_VERTICAL_AND_LEFT, 16#2563). %% ╣ 
-define(BOX_DRAWINGS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE, 16#2564). %% ╤ 
-define(BOX_DRAWINGS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE, 16#2565). %% ╥ 
-define(BOX_DRAWINGS_DOUBLE_DOWN_AND_HORIZONTAL, 16#2566). %% ╦ 
-define(BOX_DRAWINGS_UP_SINGLE_AND_HORIZONTAL_DOUBLE, 16#2567). %% ╧ 
-define(BOX_DRAWINGS_UP_DOUBLE_AND_HORIZONTAL_SINGLE, 16#2568). %% ╨ 
-define(BOX_DRAWINGS_DOUBLE_UP_AND_HORIZONTAL, 16#2569). %% ╩ 
-define(BOX_DRAWINGS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE, 16#256A). %% ╪ 
-define(BOX_DRAWINGS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE, 16#256B). %% ╫ 
-define(BOX_DRAWINGS_DOUBLE_VERTICAL_AND_HORIZONTAL, 16#256C). %% ╬ 
%%
%% Character cell arcs
%%
-define(BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_RIGHT, 16#256D). %% ╭ 
-define(BOX_DRAWINGS_LIGHT_ARC_DOWN_AND_LEFT, 16#256E). %% ╮ 
-define(BOX_DRAWINGS_LIGHT_ARC_UP_AND_LEFT, 16#256F). %% ╯ 
-define(BOX_DRAWINGS_LIGHT_ARC_UP_AND_RIGHT, 16#2570). %% ╰ 
-define(BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_RIGHT_TO_LOWER_LEFT, 16#2571). %% ╱ 
-define(BOX_DRAWINGS_LIGHT_DIAGONAL_UPPER_LEFT_TO_LOWER_RIGHT, 16#2572). %% ╲ 
-define(BOX_DRAWINGS_LIGHT_DIAGONAL_CROSS, 16#2573). %% ╳ 
%%
%% Light and heavy half lines
%%
-define(BOX_DRAWINGS_LIGHT_LEFT, 16#2574). %% ╴ 
-define(BOX_DRAWINGS_LIGHT_UP, 16#2575). %% ╵ 
-define(BOX_DRAWINGS_LIGHT_RIGHT, 16#2576). %% ╶ 
-define(BOX_DRAWINGS_LIGHT_DOWN, 16#2577). %% ╷ 
-define(BOX_DRAWINGS_HEAVY_LEFT, 16#2578). %% ╸ 
-define(BOX_DRAWINGS_HEAVY_UP, 16#2579). %% ╹ 
-define(BOX_DRAWINGS_HEAVY_RIGHT, 16#257A). %% ╺ 
-define(BOX_DRAWINGS_HEAVY_DOWN, 16#257B). %% ╻ 
%%
%% Mixed light and heavy lines
%%
-define(BOX_DRAWINGS_LIGHT_LEFT_AND_HEAVY_RIGHT, 16#257C). %% ╼ 
-define(BOX_DRAWINGS_LIGHT_UP_AND_HEAVY_DOWN, 16#257D). %% ╽ 
-define(BOX_DRAWINGS_HEAVY_LEFT_AND_LIGHT_RIGHT, 16#257E). %% ╾ 
-define(BOX_DRAWINGS_HEAVY_UP_AND_LIGHT_DOWN, 16#257F). %% ╿ 

-endif.
